### ISSUE TITLE
Let user choose name of branch: master vs. main

### ISSUE THREAD

**Issue by andreas-vester** [bttger/contributing-gen#3]
Many projects decide to use the name ``main`` (rather than ``master``) for their main branch. Your template refers to ``master``, which is also hard-coded.

https://github.com/bttger/contributing-gen/blob/2d11648a5547ac456efc0f7d0db6e1bc6b3ccb03/templates/contributing.dot#L32

I suggest to make it a variable and let the user choose the appropriate name.

**Comment by bttger** [comment]
Absolutely! Would you like to create a PR for it?

I'd also need to update the frontend project with the respective variable (and visual switch). But that project needs quite some updates... It hasn't seen updates for a long time and Vue and the project's dependencies developed a lot over time.
